cmd/proxy: main_test.go fix compilation error
With Go 1.20 the code does not compile due to the following error.

cmd/proxy/main_test.go:161:4: (*testing.common).Fatalf format %q has arg servPriv of wrong type *crypto/rsa.PrivateKey