Close connection after 5 consecutive errors
If we miss a persistent error in isCloseable the goroutine keeps spinning generating huge amounts of error messages never progressing.
This patch limits the consecutive errors to 5.

Example of such behaviour is receiving TLS bad certificate alert.

DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
ERROR: failed to read request: remote error: tls: bad certificate
DEBUG: waiting for request: 172.25.0.4:40700
(cherry picked from commit 277d94f88dc123faf8fe70ca78adb9997cf90e56)